#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.5.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# operating system (build VM template)
os: Windows Server 2016
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# set up environment
# environment:
#   COVERALLS_REPO_TOKEN:
#     secure: F5G6XI+z7nKUA1mmtD1Het6Yq5KltVlXKSTmKf2KrF+hDOyNp09V9Oozs3HuptWx

# build cache to preserve files/folders between builds
cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

#---------------------------------#
#       build configuration       #
#---------------------------------#

# set up environment
environment:
  EnableNuGetPackageRestore: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# install a few prereqs
# install:
#   - cinst opencover -source https://nuget.org/api/v2/
#   - cinst coveralls.net -source https://nuget.org/api/v2/

# restore NuGet packages before building
before_build:
  - nuget restore src\NClap.sln

# build!
build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\NClap.sln          # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: detailed

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# test_script:
#   - ps: OpenCover.Console.exe -register:user "-target:C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "-targetargs:src\NClap.Tests\bin\$env:CONFIGURATION\NClap.Tests.dll /logger:Appveyor" -skipautoprops "-filter:+[NClap]*" -output:coverage_$env:CONFIGURATION.xml 
#   - ps: csmacnz.Coveralls.exe --opencover -i coverage_$env:CONFIGURATION.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --useRelativePaths

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # publish coverage data
  # - path: coverage_release.xml
  #   name: CodeCoverageData

  # publish NuGet packages
  - path: 'src\NClap\bin\$(Configuration)\*.nupkg' # find all NuGet packages recursively
    name: NuGetPackages
